### ISSUE TITLE
Possible corruption in the 1.20.4 jar:  java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by VRXDev2** [Dreeam-qwq/Leaf#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

After switching to Leaf from Purpur 1.20.4, we've been getting warnings from plugins like FastAsyncWorldEdit, MythicCrucible or MythicMobs that say that some zip file is closed, as in the warning below:
```

[MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.player.PlayerItemDamageEvent
[11:31:05 WARN]: java.lang.IllegalStateException: zip file closed
[11:31:05 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[11:31:05 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[11:31:05 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[11:31:05 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[11:31:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[11:31:05 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[11:31:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[11:31:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[11:31:05 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[11:31:05 WARN]:        at MythicCrucible-Dist-2.0.0.jar//io.lumine.mythiccrucible.items.durability.DurabilityListener.lambda$registerEvents$0(DurabilityListener.java:50)
[11:31:05 WARN]:        at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[11:31:05 WARN]:        at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[11:31:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72)
[11:31:05 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:68)
[11:31:05 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[11:31:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616)
[11:31:05 WARN]:        at net.minecraft.world.item.ItemStack.hurt(ItemStack.java:661)
[11:31:05 WARN]:        at net.minecraft.world.item.ItemStack.a(ItemStack.java:699)
[11:31:05 WARN]:        at net.minecraft.world.entity.EntityLiving.H(EntityLiving.java:3681)
[11:31:05 WARN]:        at net.minecraft.world.entity.EntityLiving.d_(EntityLiving.java:3551)
[11:31:05 WARN]:        at net.minecraft.world.entity.player.EntityHuman.d_(EntityHuman.java:619)
[11:31:05 WARN]:        at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:3175)
[11:31:05 WARN]:        at net.minecraft.world.entity.player.EntityHuman.l(EntityHuman.java:309)
[11:31:05 WARN]:        at net.minecraft.server.level.EntityPlayer.m(EntityPlayer.java:791)
[11:31:05 WARN]:        at net.minecraft.server.network.PlayerConnection.e(PlayerConnection.java:370)
[11:31:05 WARN]:        at net.minecraft.network.NetworkManager.d(NetworkManager.java:603)
[11:31:05 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:234)
[11:31:05 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1734)
[11:31:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:494)
[11:31:05 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1530)
[11:31:05 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[11:31:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308)
[11:31:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

While it doesn't completely break plugins, it does affect many of their features (for example, in FastAsyncWorldEdit you no longer are able to do any edits, like you would normally)

### Expected behaviour

No warnings in plugins.

### To Reproduce

I don't know what can be done to reproduce it exactly, it seems to happen randomly and restarting the server fixes it.
So I suppose just try installing FastAsyncWorldEdit and/or MythicMobs on a fresh server and just test if the plugins work properly once in a while.

### Plugin list

[11:34:22 INFO]: Paper Plugins: (2):
[11:34:22 INFO]:  - LibreLogin, NookureStaff
[11:34:22 INFO]: Bukkit Plugins: (104):
[11:34:22 INFO]:  - ajLeaderboards, AlonsoTags, Analyse, AntiAA, Arceon, AxInventoryRestore, AxiomPaper, AxSellwands, AxTrade, BetterRTP
[11:34:22 INFO]:  BetterTeams, BloomAAT, BloomVouchers, ChatEmojis, ChatFilter, ChatManager, Citizens, CoinsEngine, ConsoleSpamFix, CoreProtect
[11:34:22 INFO]:  DecentHolograms, DeluxeCoinflip, DiscordSRV, DiscordSRVUtils, eShulkerBox, Essentials, EssentialsSpawn, EvoDragons, ExcellentCrates, ExcellentShop
[11:34:22 INFO]:  FastAsyncWorldEdit, FastChunkPregenerator, FasterCrystals, *FlamePearls, floodgate, FreedomChat, Geyser-Spigot, goBrush, HeadDatabase, Infiniteannouncements
[11:34:22 INFO]:  InteractiveChat, InteractiveChatDiscordSrvAddon, InvSeePlusPlus, InvSeePlusPlus_Clear, ItemEdit, LibsDisguises, LimitCrafting, LiteBans, LPC, LuckPerms
[11:34:22 INFO]:  MiniMOTD, Mjolnir, Multiverse-Core, MythicCrucible, MythicMobs, MythicSkriptAddon, nAntiBot, NBTAPI, NexEngine, nightcore
[11:34:22 INFO]:  NotBounties, PinataParty, PizzaHomes, PizzaSMP-Bot, Pl-Hide-Pro, PlaceholderAPI, Plan, PlayerKits2, PluginManager, PremiumVanish
[11:34:22 INFO]:  ProtocolLib, PvPManager, RayTraceAntiXray, ShopGUIPlus, ShopGUIPlus-SellGUI, *SimpleStaffChat, SimpleTpa, SkBee, SkinsRestorer, SkQuery
[11:34:22 INFO]:  skRayFall, Skript, skript-placeholders, skript-reflect, skript-yaml, spark, SunLight, TAB, Tebex, ToastedAFK
[11:34:22 INFO]:  UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, VirtualSpawner, VoidGen, Votifier, VotingPlugin, Vulcan, Watson
[11:34:22 INFO]:  WorldEditSUI, WorldGuard, WorldGuardExtraFlags, zKoth

### Leaf Version

This server is running Leaf version git-Leaf-"83c2468" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 83c2468 on ver/1.20.4)

**Comment by Dreeam-qwq** [comment]
Try to re-download these plugins jar

**Comment by Dreeam-qwq** [comment]
Closed since can not replicate. Welcome to reopen it if you met this issue on latest Leaf 1.20.4 / 1.21.1 (and also provide steps to replicate).
