### ISSUE TITLE
 不兼容Citizens2

### ISSUE THREAD

**Issue by Cqmmls** [Dreeam-qwq/Leaf#126]
### 自我检查表

- [X] 我已经浏览过Issue, 并确保汇报的不是已知问题
- [X] 我勾选了所有框, 因为我根本就没仔细看他们是什么
- [X] 我正在使用从 https://github.com/Winds-Studio/Leaf/releases 下载的最新 Leaf 构建
- [X] 我无法在 [Purpur 最新构建](https://purpurmc.org/) 上复现此问题

### 问题描述

[09:47:53 WARN]: Exception in thread "Leaf Async Tracker Thread - 0" java.lang.NullPointerException: Cannot read field "connection" because "entityplayer" is null
[09:47:53 WARN]:        at Citizens-2.0.35.jar//net.citizensnpcs.nms.v1_21_R1.util.CitizensEntityTracker.updatePlayer(CitizensEntityTracker.java:75)
[09:47:53 WARN]:        at net.minecraft.server.level.ChunkMap$TrackedEntity.moonrise$tick(ChunkMap.java:1185)
[09:47:53 WARN]:        at org.dreeam.leaf.async.tracker.MultithreadedTracker.lambda$tickAsync$0(MultithreadedTracker.java:70)
[09:47:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:47:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:47:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[09:47:55 WARN]: Exception in thread "Leaf Async Tracker Thread - 1" java.lang.NullPointerException
[09:48:00 WARN]: Exception in thread "Leaf Async Tracker Thread - 2" java.lang.NullPointerException

### 所期望的行为

 不兼容Citizens2

### 如何复现？

 不兼容Citizens2

### Spark profiler 链接

.

### 错误日志 (如存在)

https://api.mclo.gs/1/raw/Ag7BGFU

**Comment by liangcha385** [comment]
请查阅配置文件
`leaf-global.yml -> asyn.async-entity-tracker.compat-mode`

另外你报告这么写会被删
> 我勾选了所有框, 因为我根本就没仔细看他们是什么

这也能体现你完全没有看配置文件

> 所期望的行为：不兼容Citizens2

你既然期望不兼容为什么要提出来这份报告

此外你没有汇报任何spark报告，这也意味着谁也不知道当前环境哪里出错了

**Comment by Dreeam-qwq** [comment]
同上
