### ISSUE TITLE
Vulcan Crashing server on startup

### ISSUE THREAD

**Issue by Godl1nk** [Dreeam-qwq/Leaf#142]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

[13:06:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.UnsupportedOperationException: null
	at it.unimi.dsi.fastutil.objects.AbstractReferenceList.remove(AbstractReferenceList.java:100) ~[fastutil-8.5.14.jar:?]
	at it.unimi.dsi.fastutil.objects.AbstractReferenceList$1.remove(AbstractReferenceList.java:180) ~[fastutil-8.5.14.jar:?]
	at it.unimi.dsi.fastutil.objects.ObjectIterators$AbstractIndexBasedIterator.remove(ObjectIterators.java:874) ~[fastutil-8.5.14.jar:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:268) ~[sparky-1.21.1.jar:1.21.1-DEV-98d7aa9]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1884) ~[sparky-1.21.1.jar:1.21.1-DEV-98d7aa9]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:534) ~[sparky-1.21.1.jar:1.21.1-DEV-98d7aa9]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[sparky-1.21.1.jar:1.21.1-DEV-98d7aa9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1329) ~[sparky-1.21.1.jar:1.21.1-DEV-98d7aa9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[sparky-1.21.1.jar:1.21.1-DEV-98d7aa9]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

### Expected behaviour

Server boot normally

### To Reproduce

Just put Vulcan on Leaf

### Spark profiler link

none

**Comment by TheFaik** [comment]
At a minimum:
- Update the kernel to the latest version
- Tell me, what version of the Vulcan plugin?

**Comment by Dreeam-qwq** [comment]
Try to replicate it on latest Leaf, and send spark profiler

**Comment by Godl1nk** [comment]
开机就crash了，没有profiler

**Comment by Dreeam-qwq** [comment]
> 开机就crash了，没有profiler

leaf都没有这个commit号，用releases里的最新的leaf，复现，有报错了再发上来，谢谢

**Comment by Godl1nk** [comment]
[latest.log](https://github.com/user-attachments/files/17556074/latest.log)

**Comment by Godl1nk** [comment]
hmm.. it works fine on leaf weird

**Comment by Godl1nk** [comment]
alr u can close this, it was my issue sry for the mistake and inconvenience
