### ISSUE TITLE
关闭服务器后报错。

### ISSUE THREAD

**Issue by mcbandao** [Dreeam-qwq/Leaf#160]
### 自我检查表

- [X] 我已经浏览过Issue, 并确保汇报的不是已知问题
- [ ] 我勾选了所有框, 因为我根本就没仔细看他们是什么
- [X] 我正在使用从 https://github.com/Winds-Studio/Leaf/releases 下载的最新 Leaf 构建
- [X] 我无法在 [Purpur 最新构建](https://purpurmc.org/) 上复现此问题

### 问题描述

关闭服务器后报错版本为1.20.2，报错如下：
ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04:16:17 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
> ERROR StatusConsoleListener An exception occurred processing Appender TerminalConsole
 java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "this.jna" is null
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:443)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:362)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.initializeTerminal(TerminalConsoleAppender.java:234)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.isAnsiSupported(TerminalConsoleAppender.java:191)
        at net.minecrell.terminalconsole.HighlightErrorConverter.format(HighlightErrorConverter.java:80)
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44)
        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:567)
        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:558)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:229)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:58)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:256)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatch(AsyncAppenderEventDispatcher.java:127)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:91)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:73)
[04:16:17 INFO]: Closing Thread Pool
[04:16:17 INFO]: Closing Server

### 所期望的行为

1

### 如何复现？

无任何插件，开服后在关闭服务器就刷这个报错。

### Spark profiler 链接

1

### 错误日志 (如存在)

https://api.mclo.gs/1/raw/jKydZr1

**Comment by Dreeam-qwq** [comment]
>  我勾选了所有框, 因为我根本就没仔细看他们是什么

不要再用奇怪的版本了，目前推荐用Leaf1.21.1
