### ISSUE TITLE
不兼容 RealisticVillagers 插件

### ISSUE THREAD

**Issue by HYDeath** [Dreeam-qwq/Leaf#18]
最新leaf版本，在Paper1.20.1-196上是正常的
报错日志：
[02:58:33 ERROR]: Entity threw exception at world:268.4926652276169,89.9375,143.2098894203241
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableSet net.minecraft.world.entity.npc.VillagerProfession.e()'
        at me.matsubara.realisticvillagers.entity.v1_20_r1.villager.ai.sensing.SecondaryPoiSensor.doTick(SecondaryPoiSensor.java:44) ~[[R][现实村民]RealisticVillagers-3.1.jar:?]
        at me.matsubara.realisticvillagers.entity.v1_20_r1.villager.ai.sensing.SecondaryPoiSensor.a(SecondaryPoiSensor.java:23) ~[[R][现实村民]RealisticVillagers-3.1.jar:?]
        at net.minecraft.world.entity.ai.sensing.Sensor.tick(Sensor.java:48) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.world.entity.ai.Brain.tickSensors(Brain.java:395) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:388) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:349) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:342) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:950) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3456) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:704) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[?:?]
        at me.matsubara.realisticvillagers.entity.v1_20_r1.villager.VillagerNPC.b_(VillagerNPC.java:1784) ~[[R][现实村民]RealisticVillagers-3.1.jar:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3117) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:460) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:392) ~[?:?]
        at me.matsubara.realisticvillagers.entity.v1_20_r1.villager.VillagerNPC.l(VillagerNPC.java:1836) ~[[R][现实村民]RealisticVillagers-3.1.jar:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1380) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$13(ServerLevel.java:868) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:848) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1539) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:494) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1402) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"b207092"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Dreeam-qwq** [comment]
加我Q2682173972, 给你试一下改过的插件

**Comment by Dreeam-qwq** [comment]
Fixed in plugin side https://github.com/Dreeam-qwq/RealisticVillagers

**Comment by Dreeam-qwq** [comment]
wont fix
