### ISSUE TITLE
 compatibility issue between Leaf core and Nova plugin

### ISSUE THREAD

**Issue by GlobamaGG** [Dreeam-qwq/Leaf#189]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

The Nova plugin does not work on the Leaf core and crashes the server, when everything works fine on PurPur

# Leaf
Error:
[sun.instrument.InstrumentationImpl] WARNING: A Java agent has been loaded dynamically (C:\Users\PK\AppData\Local\Temp\byteBuddyAgent16778140128120180511.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
[14:20:55] [Server thread/ERROR]: [Nova] An exception occurred during initialization
xyz.xenondevs.nova.patch.PatcherException: 
    JDK: 22.0.1 by Oracle Corporation
    JVM: Java HotSpot(TM) 64-Bit Server VM, 22.0.1+8-16 by Oracle Corporation
    Operating system: Windows 10, amd64
    Startup parameters: [-Xms1024M, -Xmx4096M]

	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.patch.Patcher.init(Patcher.kt:88) ~[Nova-0.17-alpha.39.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[?:?]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[?:?]
	at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:54) ~[?:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.initialize.InitializableFunction.run(Initializable.kt:157) ~[Nova-0.17-alpha.39.jar:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1$1.invokeSuspend(Initializer.kt:270) ~[Nova-0.17-alpha.39.jar:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1$1.invoke(Initializer.kt) ~[Nova-0.17-alpha.39.jar:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1$1.invoke(Initializer.kt) ~[Nova-0.17-alpha.39.jar:?]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42) ~[?:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164) ~[?:?]
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source) ~[?:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.initialize.Initializer$launch$1.invokeSuspend(Initializer.kt:266) ~[Nova-0.17-alpha.39.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) ~[?:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263) ~[?:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[?:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[?:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[?:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47) ~[?:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[?:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.initialize.Initializer.initPreWorld(Initializer.kt:187) ~[Nova-0.17-alpha.39.jar:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.initialize.Initializer.start(Initializer.kt:66) ~[Nova-0.17-alpha.39.jar:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.Nova.onEnable(Nova.kt:67) ~[Nova-0.17-alpha.39.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: xyz.xenondevs.nova.patch.AssembleException: Failed to assemble class net/minecraft/world/level/levelgen/feature/OreFeature
Related transformers: xyz.xenondevs.nova.patch.impl.worldgen.NovaRuleTestPatch@4390e86
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.patch.Patcher.runTransformers(Patcher.kt:136) ~[Nova-0.17-alpha.39.jar:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.patch.Patcher.init(Patcher.kt:84) ~[Nova-0.17-alpha.39.jar:?]
	... 35 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.objectweb.asm.Frame.merge(Frame.java:1280) ~[asm-9.7.1.jar:9.7.1]
	at org.objectweb.asm.Frame.merge(Frame.java:1244) ~[asm-9.7.1.jar:9.7.1]
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1612) ~[asm-9.7.1.jar:9.7.1]
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548) ~[asm-9.7.1.jar:9.7.1]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767) ~[asm-tree-9.7.1.jar:9.7.1]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647) ~[asm-tree-9.7.1.jar:9.7.1]
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:468) ~[asm-tree-9.7.1.jar:9.7.1]
	at xyz.xenondevs.bytebase.jvm.ClassWrapper.assemble(ClassWrapper.kt:101) ~[?:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.patch.Patcher.runTransformers(Patcher.kt:134) ~[Nova-0.17-alpha.39.jar:?]
	at Nova-0.17-alpha.39.jar/xyz.xenondevs.nova.patch.Patcher.init(Patcher.kt:84) ~[Nova-0.17-alpha.39.jar:?]
	... 35 more
[14:20:55] [Server thread/ERROR]: [Nova] Initialization failure

# PurPur
![image](https://github.com/user-attachments/assets/e9c2ef52-54c3-4f17-86a3-62ae0753412e)

### Expected behaviour

the plugin will run just as well as on PurPur

### To Reproduce

1.Download Nova latest version 1.21.1(https://modrinth.com/plugin/nova-framework/version/0.17-alpha.39)

2.Download Leaf 1.21.1-DEV-890793b

3.Start the server
4. The server goes down

### Spark profiler link

the server does not start

### Error log (if applicable)

https://mclo.gs/oeYUCHB

**Comment by Taiyou06** [comment]
Just an FYI, It works fine on 1.21.4.
Will look into fixing it on 1.21.1 as well.

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/Leaf/commit/4ff90891a53492a65f8f50f14e67b825b36b48b9 and https://github.com/Winds-Studio/Leaf/commit/24093972ba08db8d010e4e6daf34a011c6a409f5
