### ISSUE TITLE
[11:32:19 INFO]: ThreadedChunkStorage: All dimensions are saved [11:32:19 INFO]: Flushing Chunk IO [11:32:19 INFO]: Closing Thread Pool 2024-04-24T03:32:19.866193600Z Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment java.lang.IllegalStateException: Unable to create a terminal

### ISSUE THREAD

**Issue by Cqmmls** [Dreeam-qwq/Leaf#46]
[11:32:19 INFO]: ThreadedChunkStorage: All dimensions are saved
[11:32:19 INFO]: Flushing Chunk IO
[11:32:19 INFO]: Closing Thread Pool
2024-04-24T03:32:19.866193600Z Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment java.lang.IllegalStateException: Unable to create a terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:394)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:362)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.initializeTerminal(TerminalConsoleAppender.java:248)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.isAnsiSupported(TerminalConsoleAppender.java:191)
        at net.minecrell.terminalconsole.HighlightErrorConverter.format(HighlightErrorConverter.java:80)
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44)
        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:567)
        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:558)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:229)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:58)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:266)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatch(AsyncAppenderEventDispatcher.java:127)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:91)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:73)
        Suppressed: java.lang.IllegalStateException: Shutdown in progress
                at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:67)
                at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:250)
                at org.jline.utils.ShutdownHooks.addHook(ShutdownHooks.java:64)
                at org.jline.utils.ShutdownHooks.add(ShutdownHooks.java:31)
                at org.jline.terminal.impl.AbstractWindowsTerminal.<init>(AbstractWindowsTerminal.java:135)
                at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.<init>(JansiWinSysTerminal.java:163)
                at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.createTerminal(JansiWinSysTerminal.java:86)
                at org.jline.terminal.impl.jansi.JansiTerminalProvider.winSysTerminal(JansiTerminalProvider.java:166)
                at org.jline.terminal.impl.jansi.JansiTerminalProvider.sysTerminal(JansiTerminalProvider.java:148)
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:428)
                ... 27 more

**Comment by Dreeam-qwq** [comment]
You can ignore this warning.

**Comment by Cqmmls** [comment]
Can you tell me what is it? I from China.

**Comment by Dreeam-qwq** [comment]
> Can you tell me what is it? I from China.

正常的报错，无视即可(

**Comment by Cqmmls** [comment]
How can I turn warning off, I don't want to see it.

**Comment by Cqmmls** [comment]
I have been follow you, guy!

**Comment by Cqmmls** [comment]
good job!

**Comment by Dreeam-qwq** [comment]
Fixed in 3669cb65e96433a41579ef384101c9acb09846f6

**Comment by Cqmmls** [comment]
Damn! You're amazing!
