### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TheFaik** [Dreeam-qwq/Leaf#78]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.
// 
// DO NOT REPORT THIS TO PAPER OR GALE! REPORT TO LEAF INSTEAD!
// 

Time: 2024-07-07 17:33:24
Description: Exception ticking world

java.lang.NullPointerException: Cannot read field "table" because "newChain" is null
	at ca.spottedleaf.concurrentutil.map.ConcurrentLong2ReferenceChainedHashTable$NodeIterator.pullResizeChain(ConcurrentLong2ReferenceChainedHashTable.java:1470)
	at ca.spottedleaf.concurrentutil.map.ConcurrentLong2ReferenceChainedHashTable$NodeIterator.findNext(ConcurrentLong2ReferenceChainedHashTable.java:1548)
	at ca.spottedleaf.concurrentutil.map.ConcurrentLong2ReferenceChainedHashTable$BaseIteratorImpl.hasNext(ConcurrentLong2ReferenceChainedHashTable.java:1404)
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:725)
	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:68)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:384)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1802)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1621)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1325)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by HaHaWTH** [comment]
What's your Leaf version? (/version command output)
Any plugins installed? 
Is it reproducible on Paper?

**Comment by TheFaik** [comment]
This server is running Leaf version 1.21-DEV-ver/1.21@1c28bb3 (2024-07-07T09:33:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
* You are 1 version(s) behind
Download the new version at: https://github.com/Winds-Studio/Leaf
Previous: 1.21-DEV-1952e41 (MC: 1.21)

Plugins:
![изображение](https://github.com/Winds-Studio/Leaf/assets/99492973/05d34275-eeba-4562-8d78-fd559af6b704)

I honestly don't know, but this error popped up when generating the world

**Comment by Dreeam-qwq** [comment]
idk (

**Comment by HaHaWTH** [comment]
Can u reproduce it on Paper?
Looks like an upstream issue (

**Comment by TheFaik** [comment]
> Can u reproduce it on Paper? Looks like an upstream issue (

Unfortunately, I have a world generation server, I can't change the core for this... But the problem is quite annoying

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/Leaf/commit/8bcdca0c072e075909d474a875e81d2e708955d7

Upstream (Paper) commit: https://github.com/PaperMC/Paper/commit/df3b6544f74be73c8882b97c43d39022340f2d74
