### ISSUE TITLE
新版22b4f73 玩家进入服务器会导致崩服

### ISSUE THREAD

**Issue by liyulong-sgy** [Dreeam-qwq/Leaf#84]
[18:42:11 ERROR]: Thread dumps:
Paper Common Worker #0:
        at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
        at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:84)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:74)
        at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
        at net.minecraft.world.level.levelgen.BitRandomSource.a(BitRandomSource.java:26)
        at net.minecraft.world.level.chunk.Chunk.<init>(Chunk.java:134)
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:231)
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask$ChunkDataLoadTask.deserialize(ChunkLoadTask.java:348)
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask$ChunkDataLoadTask.completeOnMainOffMain(ChunkLoadTask.java:311)
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask$ChunkDataLoadTask.completeOnMainOffMain(ChunkLoadTask.java:275)
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:318)
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:312)
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62)
[18:42:11 ERROR]: [ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask] Failed to parse chunk data for task: GenericDataLoadTask{class: ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask$ChunkDataLoadTask, world: world, chunk: (-82,176), hashcode: 1255563786, priority: NORMAL, type: CHUNK_DATA}, chunk data will be lost
net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:80) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:26) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at net.minecraft.world.level.chunk.LevelChunk.<init>(LevelChunk.java:134) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.read(ChunkSerializer.java:231) ~[?:?]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask$ChunkDataLoadTask.deserialize(ChunkLoadTask.java:348) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask$ChunkDataLoadTask.completeOnMainOffMain(ChunkLoadTask.java:311) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkLoadTask$ChunkDataLoadTask.completeOnMainOffMain(ChunkLoadTask.java:275) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:318) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:312) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:76) ~[leaf-1.21.jar:1.21-DEV-22b4f73]
        ... 12 more

**Comment by Dreeam-qwq** [comment]
leaf配置里的faster random generator开了试试？

**Comment by liyulong-sgy** [comment]
好的 已经正常了

**Comment by Dreeam-qwq** [comment]
should fixed in https://github.com/Winds-Studio/Leaf/commit/6f90851f57af2c876adea1e8fc4b6c2371305114
