### ISSUE TITLE
Starup error

### ISSUE THREAD

**Issue by pjindras** [Dreeam-qwq/Leaf#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

08:30:35[WARN] Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: No key feature_seed in MapLike[{bonus_chest:0b,dimensions:{"minecraft:overworld":{generator:{biome_source:{preset:"minecraft:overworld",type:"minecraft:multi_noise"},settings:"minecr
aft:overworld",type:"minecraft:noise"},type:"minecraft:overworld"},"minecraft:the_end":{generator:{biome_source:{type:"minecraft:the_end"},settings:"minecraft:end",type:"minecraft:noise"},type:"minecraft:the_end"},"minecraft:the_nether":{generator:{biome_s
ource:{preset:"minecraft:nether",type:"minecraft:multi_noise"},settings:"minecraft:nether",type:"minecraft:noise"},type:"minecraft:the_nether"}},generate_features:1b,seed:8863690350047167826L}]
at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
at net.minecraft.server.Main.main(Main.java:311) ~[leaf-1.21.jar:1.21-DEV-2149923]
at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[leaf-1.21.jar:1.21-DEV-2149923]
at org.dreeam.leaf.LeafBootstrap.boot(LeafBootstrap.java:11) ~[leaf-1.21.jar:1.21-DEV-2149923]
at org.bukkit.craftbukkit.Main.main(Main.java:296) ~[leaf-1.21.jar:1.21-DEV-2149923]
at cn.dreeam.leaper.QuantumLeaper.lambda$main$0(QuantumLeaper.java:41) ~[server.jar:?]
at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: No key feature_seed in MapLike[{bonus_chest:0b,dimensions:{"minecraft:overworld":{generator:{biome_source:{preset:"minecraft:overworld",type:"minecraft:multi_noise"},settings:"minecraft:overworld",type:"minecraft
:noise"},type:"minecraft:overworld"},"minecraft:the_end":{generator:{biome_source:{type:"minecraft:the_end"},settings:"minecraft:end",type:"minecraft:noise"},type:"minecraft:the_end"},"minecraft:the_nether":{generator:{biome_source:{preset:"minecraft:nethe
r",type:"minecraft:multi_noise"},settings:"minecraft:nether",type:"minecraft:noise"},type:"minecraft:the_nether"}},generate_features:1b,seed:8863690350047167826L}]
at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
at net.minecraft.world.level.storage.LevelStorageSource.getLevelDataAndDimensions(LevelStorageSource.java:164) ~[leaf-1.21.jar:1.21-DEV-2149923]
at net.minecraft.server.Main.lambda$main$0(Main.java:284) ~[leaf-1.21.jar:1.21-DEV-2149923]
at net.minecraft.server.WorldLoader.load(WorldLoader.java:41) ~[leaf-1.21.jar:1.21-DEV-2149923]
at net.minecraft.server.Main.lambda$main$1(Main.java:279) ~[leaf-1.21.jar:1.21-DEV-2149923]
at net.minecraft.Util.blockUntilDone(Util.java:906) ~[leaf-1.21.jar:1.21-DEV-2149923]
at net.minecraft.Util.blockUntilDone(Util.java:901) ~[leaf-1.21.jar:1.21-DEV-2149923]
at net.minecraft.server.Main.main(Main.java:278) ~[leaf-1.21.jar:1.21-DEV-2149923]
... 5 more

After that, the server cannot start.

I am using latest leaf release, minecraft 1.21.
I am not using any datapacks.
I am using secure seed.

### Expected behaviour

Server should start without error.

### To Reproduce

I dont know

### Plugin list

Cannot use /pl, server cannot start, full startup log: https://mclo.gs/aPZUYGq

### Leaf Version

Latest

### Error log (if applicable)

https://mclo.gs/07HkoPr

### Configuration

https://mclo.gs/YYaCRV5

**Comment by Dreeam-qwq** [comment]
Disable `secure-seed` in Leaf config, please read its comment before enabling it

**Comment by pjindras** [comment]
# Once you enable secure seed, all ores and structures are generated with 1024-bit seed
  # instead of using 64-bit seed in vanilla, made seed cracker become impossible.
  # WARNING! You need to backup your server and prepare a new world if you want to enable it,
  # at least for now.
  
  Yes but it is a new world, which was made with secure seed enabled, I can try to remove world and make it again, it is testing server, but in real production, it could be problem for me.

**Comment by Dreeam-qwq** [comment]
If you enabled secure seed, and run the server to generate a new world, then this error would not occur.

unless you switched to another server software and switched back, or disabled secure seed and enabled it again.
